##########################################################################################
# Configuration file for Snakemake pipeline
# Author: Redwan Farooq
# Complete ALL entries in sections marked 'REQUIRED'
# Comment ('#') any unused entries in sections marked 'OPTIONAL'
##########################################################################################


# --------------------------------------------------
# Module
# --------------------------------------------------
# REQUIRED
# Pipeline module for library preparation protocol
# Options:
#   tea_seq: TEA-seq protocol
#     Additional required configuration:
#       - 'tags' (metadata files)
#       - 'gex_barcode_whitelist' (reference files)
#       - 'atac_barcode_whitelist' (reference files)
#   cite_seq: CITE-seq protocol
#     Additional required configuration:
#       - 'tags' (metadata files)
#       - 'gex_barcode_whitelist' (reference files)
#   gex_atac: 10X multiome (GEX + ATAC) protocol
#       - 'gex_barcode_whitelist' (reference files)
#       - 'atac_barcode_whitelist' (reference files)
#   gex_fb: 10X feature barcoding (GEX + FB) protocol
#     Additional required configuration:
#     - 'features' (metadata files)
module: gex_fb

# --------------------------------------------------
# Input/output directories
# --------------------------------------------------
# REQUIRED
# Raw sequencing runs directory
run_dir: /project/fuggerlab/shared/runs
# Pipeline output directory
output_dir: /project/fuggerlab/shared/jurkat_crispri/gex_fb/test_02

# OPTIONAL
# If 'scripts_dir' not specified, defaults to
# 'resources/scripts'
# scripts_dir:
# If 'metadata_dir' not specified, defaults to
# 'metadata'
# metadata_dir:


# --------------------------------------------------
# Metadata files
# *** RELATIVE paths from 'metadata_dir' ***
# --------------------------------------------------
# REQUIRED
# Runs summary table in CSV format
# Required fields:
#   run: run folder name
#   lib_type: library type
#   donor: donor ID
#   hash: hash ID
#   sample_index: EITHER index name OR i7 index sequence
#   lane: EITHER lane number OR * (for all lanes)
runs: runs.csv

# OPTIONAL
# BarCounter antibody tag list
# tags: barcounter/tags.csv
# Cell Ranger feature reference
features: cellranger/features.csv


# --------------------------------------------------
# Reference files
# *** ABSOLUTE paths ***
# --------------------------------------------------
# REQUIRED
# Cell Ranger/STARsolo/chromap genome reference package
cellranger_reference: /databank/10x-rangers/refdata-gex-GRCh38-2020-A # Cell Ranger
# cellranger_reference: /databank/10x-rangers/refdata-cellranger-arc-GRCh38-2020-A-2.0.0 # Cell Ranger ARC
# starsolo_reference: /project/fuggerlab/rfarooq/ref/genomes/GRCh38/star # STARSolo
# chromap_reference: /databank/10x-rangers/refdata-cellranger-arc-GRCh38-2020-A-2.0.0/fasta/genome.fa # chromap
# chromap_index: /project/fuggerlab/rfarooq/ref/genomes/GRCh38/chromap/index # chromap

# OPTIONAL
# If 'dual_index_kits' and 'single_index_kits' not
# provided, index name parsing will not be performed
# and all sample indexes in runs table will be
# interpreted as literal i7 index sequences
dual_index_kits:
  - /project/fuggerlab/rfarooq/ref/sample_index_kits/10X_Dual_Index_Kit_TT_Set_A.csv
  # - /project/fuggerlab/rfarooq/ref/sample_index_kits/10X_Dual_Index_Kit_TS_Set_A.csv
  # - /project/fuggerlab/rfarooq/ref/sample_index_kits/10X_Dual_Index_Kit_TN_Set_A.csv
  - /project/fuggerlab/rfarooq/ref/sample_index_kits/10X_Dual_Index_Kit_NT_Set_A.csv
  # - /project/fuggerlab/rfarooq/ref/sample_index_kits/10X_Dual_Index_Kit_NN_Set_A.csv
single_index_kits:
#   - /project/fuggerlab/rfarooq/ref/sample_index_kits/10X_Single_Index_Kit_T_Set_A.csv
#   - /project/fuggerlab/rfarooq/ref/sample_index_kits/10X_Single_Index_Kit_N_Set_A.csv
#   - /project/fuggerlab/rfarooq/ref/sample_index_kits/Illumina_Single_Index_Kit_D.csv
  - /project/fuggerlab/rfarooq/ref/sample_index_kits/Illumina_Single_Index_Kit_RPI.csv
# Cell barcode whitelist
# gex_barcode_whitelist: /project/fuggerlab/rfarooq/ref/barcode_whitelists/3M-february-2018.txt.gz # 10x 3' v3
# gex_barcode_whitelist: /project/fuggerlab/rfarooq/ref/barcode_whitelists/737K-arc-v1.txt.gz # 10x multiome v1 (GEX)
# atac_barcode_whitelist: /project/fuggerlab/rfarooq/ref/barcode_whitelists/737K-arc-v1_atac.txt.gz # 10x multiome v1 (ATAC)

# --------------------------------------------------
# Script parameters
# --------------------------------------------------
# OPTIONAL
# If 'reverse_complement' not provided, defaults to
# False; set to True if sequencer workflow reads i5
# index in reverse complement e.g.
#   NovaSeq6000 with v1.0 reagent kits
#   iSeq100
#   MiniSeq with standard reagent kits
#   NextSeq
#   HiSeq X/4000/3000
reverse_complement: true


# --------------------------------------------------
# Command line flags
# --------------------------------------------------
# OPTIONAL
# If not specified, defaults to ''
bcl2fastq_args: >-
  --create-fastq-for-index-reads
  --minimum-trimmed-read-length=6
  --mask-short-adapter-reads=6
  --ignore-missing-positions
  --ignore-missing-filter
  --ignore-missing-bcls
cellranger_args: >-
  --nosecondary
  --disable-ui
starsolo_args: >-
  --sysShell /bin/bash
  --readFilesCommand zcat
  --clipAdapterType CellRanger4
  --outFilterScoreMin 30
  --outSAMtype BAM SortedByCoordinate
  --soloType CB_UMI_Simple
  --soloCellFilter None
  --soloFeatures GeneFull_Ex50pAS
  --soloStrand Forward
  --soloCBstart 1
  --soloCBlen 16
  --soloUMIstart 17
  --soloUMIlen 12
  --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts
  --soloUMIfiltering MultiGeneUMI_CR
  --soloUMIdedup 1MM_CR  
chromap_args: >-
  --preset atac
  --read-format bc:8:-1:-
  --barcode-translate /project/fuggerlab/rfarooq/ref/barcode_whitelists/737K-arc-v1_translation.tsv
macs2_args: >-
  -f BED
  -g hs
  --nomodel
  --extsize 200
  --shift -100
  --keep-dup all
fastqc_args: --noextract
multiqc_args: -zfd --dirs-depth=1 --interactive


# --------------------------------------------------
# Miscellaneous parameters
# --------------------------------------------------
# OPTIONAL
# If 'bases_mask' not provided, defaults to read
# type/length specified in RunInfo.xml file in
# Illumina run folder
bases_mask:
  GEX: Y28n*,I10n*,I10n*,Y90n*
  # ATAC: Y50n*,I8n*,Y16n*,Y50n*
  # ADT: Y28n*,I6n*,n*,Y15n*
  HTO: Y28n*,I6n*,n*,Y15n*
  CRISPR: Y28n*,I10n*,I10n*,Y90n*
