##########################################################################################
# Module rule specifications file for Snakemake preprocessing pipeline
# Author: Redwan Farooq
##########################################################################################

# --------------------------------------------------
# Modules
# --------------------------------------------------
# Available pipeline module names and lists of rule
# names (as per *.smk file names) in each module
tea_seq:
  - bcl2fastq
  - fastqc
  - multiqc
  - count_reads
  - starsolo
  - chromap
  - macs2
  - barcounter
  - mapping_qc
tea_seq_cellranger_arc:
  - bcl2fastq
  - fastqc
  - multiqc
  - count_reads
  - cellranger_arc
  - barcounter
  - mapping_qc
cite_seq:
  - bcl2fastq
  - fastqc
  - multiqc
  - count_reads
  - starsolo
  - barcounter
  - mapping_qc
gex_atac:
  - bcl2fastq
  - fastqc
  - multiqc
  - count_reads
  - starsolo
  - chromap
  - macs2
  - mapping_qc
gex_atac_cellranger_arc:
  - bcl2fastq
  - fastqc
  - multiqc
  - count_reads
  - cellranger_arc
gex_fb:
  - bcl2fastq
  - fastqc
  - multiqc
  - count_reads
  - cellranger
